### ISSUE TITLE
Fitting date on PA is not auto-populating when item is set. 

### ISSUE THREAD

**Issue by anstill79** [anstill79/FMP-HAC-App#1]

**Comment by anstill79** [comment]
Should setting fit date of item also set all others in same fitting, as long as all else are blank?

**Comment by christinevong** [comment]
Accessory auto-populates into the PA form. 

![image](https://github.com/anstill79/FMP-HAC-App/assets/139992350/365e6706-5e55-44e4-9b75-cfc94def21ea)
![image](https://github.com/anstill79/FMP-HAC-App/assets/139992350/4b8665e1-5b48-4c75-8ee3-b95b02d1d7ae)

**Comment by christinevong** [comment]
Trial ends date doesn't auto-populate on the PA form.
