### ISSUE TITLE
"Other Fitting" pop-up window vs "Fitting Link" hyperlink

### ISSUE THREAD

**Issue by christinevong** [anstill79/FMP-HAC-App#25]
When I click on any of these devices from the "Other Fitting" box..... ![image](https://github.com/anstill79/FMP-HAC-App/assets/139992350/ff478d15-422e-47b6-9b2e-c30a95f2ccba)

I get a blank page:
![image](https://github.com/anstill79/FMP-HAC-App/assets/139992350/33721fa8-b1fa-4544-9d53-3ab3dc13fb0f)

---------VERSUS---------------------------------------------------------------------------------------------------
When I click on the "Fitting List" hyperlink on the top, it leads me to the fitting list page. 

![image](https://github.com/anstill79/FMP-HAC-App/assets/139992350/898b31e7-9604-4c4b-9bf4-7c49bfd06ffa)

![image](https://github.com/anstill79/FMP-HAC-App/assets/139992350/f539031e-30e9-486f-a9b6-6e7e60bd43e5)

From there, if I click on any devices, I can view the hearing aid info on this page. 

![image](https://github.com/anstill79/FMP-HAC-App/assets/139992350/f8ef421a-5bef-47a5-adb8-9895142291fe)

**Comment by anstill79** [comment]
All fixed
