### ISSUE TITLE
Accessory on PA

### ISSUE THREAD

**Issue by christinevong** [anstill79/FMP-HAC-App#3]
The name of the accessory and receiver power don't show up on the PA form. 

![853a0d9d-e799-4004-857c-aa575c6980aa](https://github.com/anstill79/FMP-HAC-App/assets/139992350/f8932ef0-4afb-4ae5-a920-516055e66040)
![fcc00f31-627e-4a55-9b0c-e2def05eb231](https://github.com/anstill79/FMP-HAC-App/assets/139992350/230f4c5b-6c85-49f2-a388-ba9be66d8f3d)

**Comment by anstill79** [comment]
Need to relate fk_primary charger in graph then grab name of acc instead of name of HA model in attach_model script (mostly an issue w chargers and not one-off accessories set to generics)
